services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: supposed-to-be-secret
      MYSQL_DATABASE: Province
    ports:
      - "3306:3306"
    volumes:
      - ~/Documentos/mysql/db-scripts:/docker-entrypoint-initdb.d

